### ISSUE TITLE
error

### ISSUE THREAD

**Issue by njust-miao** [XiaoLaoDi/maskscoring_rcnn#1]
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    from predictor import COCODemo
  File "/home/mxy/maskscoring_rcnn/predictor.py", line 11, in <module>
    from maskrcnn_benchmark.utils import cv2_util
ImportError: cannot import name 'cv2_util' from 'maskrcnn_benchmark.utils' (/home/mxy/maskscoring_rcnn/maskrcnn_benchmark/utils/__init__.py)

I meet this error and dont know how to solve,could you help me?

**Comment by w11m** [comment]
same problem anyone know how to fix it?

**Comment by w11m** [comment]
i fixed the issue just go to https://github.com/facebookresearch/maskrcnn-benchmark/tree/master/maskrcnn_benchmark/utils to get the cv2_util.py
